#!/usr/bin/env bash
# This script installs nginx on ubuntu server

apt-get update
apt-get install nginx -y
sudo ufw allow 'nginx HTTP'
sh -c 'echo Hello World! > var/www/html/index.html'
service nginx restart
