#!/usr/bin/env bash
# This script installs nginx on ubuntu server

apt-get update -y
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me http://s1dd.tech permanent;' /etc/nginx/sites-available/default
service nginx restart
