#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page.

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me http://s1dd.tech permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
